import type { MetricCard, VaultItem } from "@/lib/types/dashboard";

export const dashboardMetrics: MetricCard[] = [
  {
    label: "Total Vaults",
    value: "12",
    sub: "3 paused",
    subColor: "text-muted",
    border: "border-primary/30",
    gradient: "from-primary/8 to-transparent",
    iconColor: "text-primary",
    iconKey: "grid",
  },
  {
    label: "Estimated TVL",
    value: "$128,430",
    sub: "+4.2% today",
    subColor: "text-success",
    border: "border-success/30",
    gradient: "from-success/8 to-transparent",
    iconColor: "text-success",
    iconKey: "coin",
  },
  {
    label: "24h Executions",
    value: "42",
    sub: "36 ✓ · 6 ✗",
    subColor: "text-muted",
    border: "border-border/60",
    gradient: "from-card-2/40 to-transparent",
    iconColor: "text-muted",
    iconKey: "chart",
  },
  {
    label: "Active Alerts",
    value: "2",
    sub: "unresolved",
    subColor: "text-warning",
    border: "border-warning/30",
    gradient: "from-warning/8 to-transparent",
    iconColor: "text-warning",
    iconKey: "bell",
  },
];

export const dashboardVaults: VaultItem[] = [
  {
    addr: "0x91f7...A4c2",
    chain: "Base Mainnet",
    status: "active",
    balance: "3,200 USDC / 0.82 WETH",
    rule: "Buy < $1,900 · Sell > $2,350",
    lastExecution: "3m ago",
    pnl: "+$4,210",
    pnlUp: true,
  },
  {
    addr: "0xA8d3...F3b7",
    chain: "Ethereum",
    status: "active",
    balance: "5,100 USDC / 0.07 WBTC",
    rule: "Buy < $60,000 · Sell > $75,000",
    lastExecution: "18m ago",
    pnl: "+$128,300",
    pnlUp: true,
  },
  {
    addr: "0x52c4...19f1",
    chain: "Arbitrum",
    status: "paused",
    balance: "1,850 USDC / 0.00 WETH",
    rule: "Rebalance: USDC/DAI",
    lastExecution: "2h ago",
    pnl: "-$1,240",
    pnlUp: false,
  },
];
